name: CI

on: [push, pull_request]

jobs:
  test:
    name: Node.js v6
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 6

    - name: Install
      run: npm install

    - name: Tests
      run: npm test