name: CI

on:
  push:
    paths:
      - 'src/**'
    branches:
      - master
  pull_request:
    paths:
      - 'src/**'
    branches:
      - master

jobs:
  test:
    name: Node.js v14
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: (env) pnpm
      run: curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node

    - name: (env) cache
      uses: actions/cache@master
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

    - name: Install
      run: pnpm install

    - name: Compiles
      run: pnpm run build

    - name: Tests
      run: pnpm run test